<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class MovieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        DB::table('movies')->truncate();

        $movies = [
            [
                'title' => 'Your Name',
                'slug' => Str::slug('Your Name'),
                'description' => 'Dua remaja yang tidak saling kenal tiba-tiba bertukar tubuh dan menjalin hubungan aneh yang melampaui waktu dan ruang.',
                'director' => 'Makoto Shinkai',
                'writers' => 'Makoto Shinkai',
                'stars' => 'Ryunosuke Kamiki, Mone Kamishiraishi',
                'poster' => 'https://i.pinimg.com/736x/32/0a/b7/320ab7994967c304099d49b9ba405a70.jpg',
                'release_date' => '2016-08-26',
                'duration' => 106,
                'url_720' => 'https://www.youtube.com/embed/PLl99DlL6b4',
                'url_1080' => 'https://www.youtube.com/embed/6hB3S9bIaco',
                'url_4k' => 'https://www.youtube.com/embed/-pHfPJGatgE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Spirited Away',
                'slug' => Str::slug('Spirited Away'),
                'description' => 'Seorang gadis kecil masuk ke dunia roh dan harus bekerja di pemandian roh untuk menyelamatkan orang tuanya.',
                'director' => 'Hayao Miyazaki',
                'writers' => 'Hayao Miyazaki',
                'stars' => 'Rumi Hiiragi, Miyu Irino',
                'poster' => 'https://i.pinimg.com/736x/fa/35/8e/fa358e86eef793031e7f9577cfeaf32f.jpg',
                'release_date' => '2001-07-20',
                'duration' => 125,
                'url_720' => 'https://www.youtube.com/embed/UaVTIH8mujA',
                'url_1080' => 'https://www.youtube.com/embed/1x0GpEZnwa8',
                'url_4k' => 'https://www.youtube.com/embed/5DO-nDW43Ik',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Weathering with You',
                'slug' => Str::slug('Weathering with You'),
                'description' => 'Seorang remaja bertemu gadis yang dapat memanipulasi cuaca di Tokyo yang dilanda hujan terus menerus.',
                'director' => 'Makoto Shinkai',
                'writers' => 'Makoto Shinkai',
                'stars' => 'Kotaro Daigo, Nana Mori',
                'poster' => 'https://i.pinimg.com/736x/28/bb/87/28bb879ccfb39c80fc8c3b70cea796a6.jpg',
                'release_date' => '2019-07-19',
                'duration' => 112,
                'url_720' => 'https://www.youtube.com/embed/EXeTwQWrcwY',
                'url_1080' => 'https://www.youtube.com/embed/LDG9bisJEaI',
                'url_4k' => 'https://www.youtube.com/embed/8gqM4BCgG8Y',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'A Silent Voice',
                'slug' => Str::slug('A Silent Voice'),
                'description' => 'Seorang mantan pengganggu mencari penebusan dengan gadis tuna rungu yang dulu ia sakiti.',
                'director' => 'Naoko Yamada',
                'writers' => 'Reiko Yoshida, Yoshitoki Ōima',
                'stars' => 'Miyu Irino, Saori Hayami',
                'poster' => 'https://i.pinimg.com/736x/80/29/47/80294717b4d93adc5d095aeed7b0f205.jpg',
                'release_date' => '2016-09-17',
                'duration' => 130,
                'url_720' => 'https://www.youtube.com/embed/s7EdQ4FqbhY',
                'url_1080' => 'https://www.youtube.com/embed/tGpTpVyI_OQ',
                'url_4k' => 'https://www.youtube.com/embed/5ZAhzsi1ybM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Demon Slayer: Mugen Train',
                'slug' => Str::slug('Demon Slayer: Mugen Train'),
                'description' => 'Tanjiro dan kawan-kawan bergabung dengan Hashira Api untuk menyelidiki serangkaian hilangnya orang di Kereta Mugen.',
                'director' => 'Haruo Sotozaki',
                'writers' => 'Koyoharu Gotouge, Ufotable',
                'stars' => 'Natsuki Hanae, Akari Kito',
                'poster' => 'https://i.pinimg.com/736x/7a/c5/c7/7ac5c7af01917b0d06147f5cb8d55fd3.jpg',
                'release_date' => '2020-10-16',
                'duration' => 117,
                'url_720' => 'https://www.youtube.com/embed/bLvqoHBptjg',
                'url_1080' => 'https://www.youtube.com/embed/uPIEn0M8su0',
                'url_4k' => 'https://www.youtube.com/embed/sAU6Istwz6c',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Howl\'s Moving Castle',
                'slug' => Str::slug('Howl\'s Moving Castle'),
                'description' => 'Seorang gadis muda dikutuk menjadi wanita tua dan tinggal di kastil penyihir eksentrik bernama Howl.',
                'director' => 'Hayao Miyazaki',
                'writers' => 'Hayao Miyazaki, Diana Wynne Jones',
                'stars' => 'Chieko Baisho, Takuya Kimura',
                'poster' => 'https://i.pinimg.com/736x/46/f9/55/46f9552430ea825fe01527f501f78393.jpg',
                'release_date' => '2004-11-20',
                'duration' => 119,
                'url_720' => 'https://www.youtube.com/embed/YoHD9XEInc0',
                'url_1080' => 'https://www.youtube.com/embed/8hP9D6kZseM',
                'url_4k' => 'https://www.youtube.com/embed/HcoZbHBDHQA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ponyo',
                'slug' => Str::slug('Ponyo'),
                'description' => 'Seorang anak laki-laki bersahabat dengan putri ikan mas ajaib yang ingin menjadi manusia.',
                'director' => 'Hayao Miyazaki',
                'writers' => 'Hayao Miyazaki',
                'stars' => 'Yuria Nara, Hiroki Doi',
                'poster' => 'https://i.pinimg.com/736x/4e/3d/80/4e3d805bb3c46870f79e6b9e4a345b5b.jpg',
                'release_date' => '2008-07-19',
                'duration' => 101,
                'url_720' => 'https://www.youtube.com/embed/qtRKdVHc-cE',
                'url_1080' => 'https://www.youtube.com/embed/BdJKm16Co6M',
                'url_4k' => 'https://www.youtube.com/embed/O1nDozs-LxI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Wind Rises',
                'slug' => Str::slug('The Wind Rises'),
                'description' => 'Kisah fiksi tentang insinyur pesawat Jiro Horikoshi yang bermimpi membuat pesawat terbang indah.',
                'director' => 'Hayao Miyazaki',
                'writers' => 'Hayao Miyazaki',
                'stars' => 'Hideaki Anno, Miori Takimoto',
                'poster' => 'https://i.pinimg.com/736x/72/23/f1/7223f1aab59d9a150440549feba9df0f.jpg',
                'release_date' => '2013-07-20',
                'duration' => 126,
                'url_720' => 'https://www.youtube.com/embed/vKQi3bBA1y8',
                'url_1080' => 'https://www.youtube.com/embed/m8e-FF8MsqU',
                'url_4k' => 'https://www.youtube.com/embed/9ix7TUGVYIo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'My Neighbor Totoro',
                'slug' => Str::slug('My Neighbor Totoro'),
                'description' => 'Dua gadis kecil bertemu makhluk hutan ajaib bernama Totoro saat pindah ke desa.',
                'director' => 'Hayao Miyazaki',
                'writers' => 'Hayao Miyazaki',
                'stars' => 'Noriko Hidaka, Chika Sakamoto',
                'poster' => 'https://i.pinimg.com/736x/d1/2c/ad/d12cadc3f62500594821be0278aef5a8.jpg',
                'release_date' => '1988-04-16',
                'duration' => 86,
                'url_720' => 'https://www.youtube.com/embed/zSWdZVtXT7E',
                'url_1080' => 'https://www.youtube.com/embed/0vxOhd4qlnA',
                'url_4k' => 'https://www.youtube.com/embed/2LqzF5WauAw',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Castle in the Sky',
                'slug' => Str::slug('Castle in the Sky'),
                'description' => 'Petualangan dua anak yang mencari kota terapung legendaris bernama Laputa.',
                'director' => 'Hayao Miyazaki',
                'writers' => 'Hayao Miyazaki',
                'stars' => 'Mayumi Tanaka, Keiko Yokozawa',
                'poster' => 'https://i.pinimg.com/736x/25/b4/f5/25b4f53025c19f1f4491dc48c3d7dafd.jpg',
                'release_date' => '1986-08-02',
                'duration' => 124,
                'url_720' => 'https://www.youtube.com/embed/owK1qxDselE',
                'url_1080' => 'https://www.youtube.com/embed/P5ieIbInFpg',
                'url_4k' => 'https://www.youtube.com/embed/b_VKnQfZX4c',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Girl Who Leapt Through Time',
                'slug' => Str::slug('The Girl Who Leapt Through Time'),
                'description' => 'Seorang siswi SMA secara tidak sengaja mendapatkan kemampuan untuk melompati waktu.',
                'director' => 'Mamoru Hosoda',
                'writers' => 'Satoko Okudera, Yasutaka Tsutsui',
                'stars' => 'Riisa Naka, Takuya Ishida',
                'poster' => 'https://i.pinimg.com/736x/45/28/3a/45283ae12d6f442f868313e9e034ee94.jpg',
                'release_date' => '2006-07-15',
                'duration' => 98,
                'url_720' => 'https://www.youtube.com/embed/V75dMMIW2B4',
                'url_1080' => 'https://www.youtube.com/embed/_e8QGuG50ro',
                'url_4k' => 'https://www.youtube.com/embed/uYnQDsaxHZU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tokyo Godfathers',
                'slug' => Str::slug('Tokyo Godfathers'),
                'description' => 'Tiga tunawisma menemukan bayi terlantar saat Natal dan memutuskan mencari orang tuanya.',
                'director' => 'Satoshi Kon',
                'writers' => 'Satoshi Kon, Keiko Nobumoto',
                'stars' => 'Toru Emori, Yoshiaki Umegaki',
                'poster' => 'https://i.pinimg.com/736x/cd/84/2d/cd842d6491a06ae898c19da849e93bb7.jpg',
                'release_date' => '2003-08-30',
                'duration' => 92,
                'url_720' => 'https://www.youtube.com/embed/TcMBFSGVi1c',
                'url_1080' => 'https://www.youtube.com/embed/hA6hldpSTF8',
                'url_4k' => 'https://www.youtube.com/embed/0jNvJU52LvU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Belle',
                'slug' => Str::slug('Belle'),
                'description' => 'Seorang gadis pemalu menjadi bintang di dunia virtual bernama "U", menghadapi misteri dan trauma masa lalu.',
                'director' => 'Mamoru Hosoda',
                'writers' => 'Mamoru Hosoda',
                'stars' => 'Kaho Nakamura, Ryo Narita',
                'poster' => 'https://i.pinimg.com/736x/a3/8c/d2/a38cd284b6016d41e2bc250f1a8bf34d.jpg',
                'release_date' => '2021-07-16',
                'duration' => 121,
                'url_720' => 'https://www.youtube.com/embed/SEUXfv87Wpk',
                'url_1080' => 'https://www.youtube.com/embed/5xH0HfJHsaY',
                'url_4k' => 'https://www.youtube.com/embed/PhPROeYAYBA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Tale of the Princess Kaguya',
                'slug' => Str::slug('The Tale of the Princess Kaguya'),
                'description' => 'Seorang bayi perempuan ditemukan dalam batang bambu dan tumbuh menjadi wanita cantik dengan takdir tragis.',
                'director' => 'Isao Takahata',
                'writers' => 'Isao Takahata, Riko Sakaguchi',
                'stars' => 'Aki Asakura, Kengo Kora',
                'poster' => 'https://m.media-amazon.com/images/M/MV5BMmNkODhkYjctMDMyOC00ZTNjLTkwZTItM2ExMTAxMGU1ZGQ1XkEyXkFqcGc@._V1_SX300.jpg',
                'release_date' => '2013-11-23',
                'duration' => 137,
                'url_720' => 'https://www.youtube.com/embed/7d_jQycdQGo',
                'url_1080' => 'https://www.youtube.com/embed/ZZY-Ytrw2co',
                'url_4k' => 'https://www.youtube.com/embed/teHfyby_veU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'When Marnie Was There',
                'slug' => Str::slug('When Marnie Was There'),
                'description' => 'Seorang gadis kesepian bertemu dengan gadis misterius bernama Marnie di rumah tepi danau.',
                'director' => 'Hiromasa Yonebayashi',
                'writers' => 'Hiromasa Yonebayashi, Keiko Niwa',
                'stars' => 'Sara Takatsuki, Kasumi Arimura',
                'poster' => 'https://i.pinimg.com/736x/3d/0c/e8/3d0ce8e25993ec611b48cd9fc84217db.jpg',
                'release_date' => '2014-07-19',
                'duration' => 103,
                'url_720' => 'https://www.youtube.com/embed/0fUCuvNlOCg',
                'url_1080' => 'https://www.youtube.com/embed/_iH0UBYDI4g',
                'url_4k' => 'https://www.youtube.com/embed/eUdM9vrCbow',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Whisper of the Heart',
                'slug' => Str::slug('Whisper of the Heart'),
                'description' => 'Seorang gadis remaja mengejar mimpinya menjadi penulis setelah menemukan inspirasi dari seorang pembuat biola.',
                'director' => 'Yoshifumi Kondō',
                'writers' => 'Hayao Miyazaki, Aoi Hiiragi',
                'stars' => 'Yoko Honna, Issei Takahashi',
                'poster' => 'https://i.pinimg.com/736x/de/a1/d8/dea1d8cadb32b7f617d74ead8ac1f94d.jpg',
                'release_date' => '1995-07-15',
                'duration' => 111,
                'url_720' => 'https://www.youtube.com/embed/o4gHCmTQDVI',
                'url_1080' => 'https://www.youtube.com/embed/RLtaA9fFNXU',
                'url_4k' => 'https://www.youtube.com/embed/ijXruSzfGEc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Secret World of Arrietty',
                'slug' => Str::slug('The Secret World of Arrietty'),
                'description' => 'Seorang anak laki-laki sakit bertemu gadis kecil dari ras makhluk mini yang tinggal di bawah rumahnya.',
                'director' => 'Hiromasa Yonebayashi',
                'writers' => 'Hayao Miyazaki, Keiko Niwa',
                'stars' => 'Mirai Shida, Ryunosuke Kamiki',
                'poster' => 'https://i.pinimg.com/736x/a9/78/45/a9784590838a3a89e6eb80f992e16277.jpg',
                'release_date' => '2010-07-17',
                'duration' => 94,
                'url_720' => 'https://www.youtube.com/embed/lB95KLmpLR4',
                'url_1080' => 'https://www.youtube.com/embed/8N4TMvz6XwQ',
                'url_4k' => 'https://www.youtube.com/embed/2RB3edZyeYw',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Children Who Chase Lost Voices',
                'slug' => Str::slug('Children Who Chase Lost Voices'),
                'description' => 'Seorang gadis remaja memulai perjalanan ke dunia bawah untuk memahami kehilangan dan cinta.',
                'director' => 'Makoto Shinkai',
                'writers' => 'Makoto Shinkai',
                'stars' => 'Hisako Kanemoto, Miyu Irino',
                'poster' => 'https://i.pinimg.com/736x/c1/71/aa/c171aacc3b4530d435ce7077d66bff49.jpg',
                'release_date' => '2011-05-07',
                'duration' => 116,
                'url_720' => 'https://www.youtube.com/embed/hEJnMQG9ev8',
                'url_1080' => 'https://www.youtube.com/embed/YWNWi-ZWL3c',
                'url_4k' => 'https://www.youtube.com/embed/cdLl1GVjOrc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '5 Centimeters per Second',
                'slug' => Str::slug('5 Centimeters per Second'),
                'description' => 'Tiga bagian cerita cinta yang menggambarkan jarak emosional dan waktu yang memisahkan dua kekasih.',
                'director' => 'Makoto Shinkai',
                'writers' => 'Makoto Shinkai',
                'stars' => 'Kenji Mizuhashi, Yoshimi Kondou',
                'poster' => 'https://i.pinimg.com/736x/f8/b2/77/f8b277e72641845c69e4c4282cd76cdb.jpg',
                'release_date' => '2007-03-03',
                'duration' => 63,
                'url_720' => 'https://www.youtube.com/embed/0pdqf4P9MB8',
                'url_1080' => 'https://www.youtube.com/embed/45TbOYFZ0Lk',
                'url_4k' => 'https://www.youtube.com/embed/je0aAf2f8XQ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Paprika',
                'slug' => Str::slug('Paprika'),
                'description' => 'Psikolog menggunakan perangkat untuk masuk ke mimpi pasien, tapi teknologi itu dicuri.',
                'director' => 'Satoshi Kon',
                'writers' => 'Seishi Minakami, Satoshi Kon',
                'stars' => 'Megumi Hayashibara, Toru Emori',
                'poster' => 'https://i.pinimg.com/736x/e2/b6/d4/e2b6d4da1914f9ed3bc0360dd2c68416.jpg',
                'release_date' => '2006-11-25',
                'duration' => 90,
                'url_720' => 'https://www.youtube.com/embed/1Fg5iWmQjwk',
                'url_1080' => 'https://www.youtube.com/embed/zru-1DbbcsA',
                'url_4k' => 'https://www.youtube.com/embed/eTdf-nHhPWM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('movies')->insert($movies);

        Schema::enableForeignKeyConstraints();
    }
}
